"""
briefing.py — Auto-generated, fully-grounded executive briefing.

Answers the brief's framing question ("would you trust this in front of an
executive?") by assembling a one-glance summary where EVERY quantitative claim
carries its source. It composes three already-verified layers:

  - latest metrics            (metrics.py / XBRL, with accession)
  - top material moves        (linkage.py, with the explaining passage)
  - data-health caveats       (conflicts.py)

Plus a cross-company "who leads, on what, by how much" ranking computed from the
same ground-truth figures. No figure is generated by an LLM; an optional LLM pass
only writes connective prose constrained to these verified inputs.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Optional

from metrics import compute_metrics, DerivedMetric
from linkage import detect_material_moves, MaterialMove
from conflicts import all_conflicts
import config

HEADLINE_METRICS = ["Gross Margin", "Operating Margin", "Net Margin",
                    "Revenue YoY Growth", "Free Cash Flow", "Debt-to-Equity",
                    "Return on Equity", "Current Ratio"]


@dataclass
class CompanyBrief:
    ticker: str
    latest_fy: int
    headline: dict          # metric -> {value, unit, accession}
    top_moves: list         # list of MaterialMove
    caveats: list[str]


def _latest_by_metric(metrics: list[DerivedMetric]) -> dict[str, DerivedMetric]:
    out: dict[str, DerivedMetric] = {}
    for m in metrics:
        if m.value is None:
            continue
        if m.name not in out or m.fy > out[m.name].fy:
            out[m.name] = m
    return out


def build_company_brief(ticker: str) -> CompanyBrief:
    metrics, _, _ = compute_metrics(ticker)
    latest = _latest_by_metric(metrics)
    headline = {}
    for name in HEADLINE_METRICS:
        m = latest.get(name)
        if m:
            headline[name] = {
                "value": m.value, "unit": m.unit, "fy": m.fy,
                "accession": m.inputs[0].accession if m.inputs else "n/a",
                "formula": m.formula,
            }
    moves = detect_material_moves(ticker, metrics)[:3]
    grouped = all_conflicts(ticker)
    caveats = [c.detail for items in grouped.values() for c in items
               if c.severity in ("high", "medium")]
    # Always include the fiscal caveat (low sev but matters for comparison).
    for c in grouped.get("fiscal_misalignment", []):
        caveats.append(c.detail)
    fy = max((h["fy"] for h in headline.values()), default=0)
    return CompanyBrief(ticker, fy, headline, moves, caveats)


def _fmt(v: float, unit: str) -> str:
    if unit == "%":
        return f"{v:.1f}%"
    if unit == "x":
        return f"{v:.2f}x"
    return f"${v:,.0f}"


def cross_company_ranking(tickers=None) -> dict[str, list[dict]]:
    """For each headline metric, rank companies by latest value with the gap."""
    tickers = tickers or config.active_tickers()
    latest_all: dict[str, dict[str, DerivedMetric]] = {}
    for tk in tickers:
        m, _, _ = compute_metrics(tk)
        latest_all[tk] = _latest_by_metric(m)

    ranking: dict[str, list[dict]] = {}
    for name in HEADLINE_METRICS:
        rows = []
        for tk in tickers:
            m = latest_all[tk].get(name)
            if m:
                rows.append({"ticker": tk, "value": m.value, "unit": m.unit,
                             "fy": m.fy,
                             "accession": m.inputs[0].accession if m.inputs else "n/a"})
        if not rows:
            continue
        # Leverage: lower is better; others higher is better.
        reverse = name != "Debt-to-Equity"
        rows.sort(key=lambda r: r["value"], reverse=reverse)
        ranking[name] = rows
    return ranking


def render_markdown_brief(ticker: str, with_llm: bool = False) -> str:
    b = build_company_brief(ticker)
    lines = [f"## {ticker} — Executive Briefing (latest FY{b.latest_fy})", ""]
    lines.append("### Headline metrics (each traceable to a filing)")
    for name, h in b.headline.items():
        lines.append(f"- **{name}: {_fmt(h['value'], h['unit'])}** "
                     f"(FY{h['fy']}, acc {h['accession']}) — `{h['formula']}`")
    lines.append("")
    lines.append("### Most material recent moves")
    if not b.top_moves:
        lines.append("- None past materiality thresholds.")
    for mv in b.top_moves:
        lines.append(f"- {mv.headline()}")
    lines.append("")
    if b.caveats:
        lines.append("### Data caveats")
        for c in b.caveats:
            lines.append(f"- {c}")
        lines.append("")

    if with_llm:
        try:
            from agent import _ollama_chat
            facts_blob = "\n".join(lines)
            sys = ("Write a 3-sentence executive summary using ONLY the verified "
                   "facts below. Do not introduce any number not present. Plain, "
                   "direct analyst tone.")
            summary = _ollama_chat(sys, facts_blob)
            lines = [f"## {ticker} — Executive Briefing (latest FY{b.latest_fy})",
                     "", "### Summary", summary, ""] + lines[2:]
        except RuntimeError:
            pass
    return "\n".join(lines)


if __name__ == "__main__":
    import config as _c
    tks=_c.active_tickers()
    print(render_markdown_brief(tks[0]))
    print("\n" + "=" * 60)
    rk = cross_company_ranking()
    for metric, rows in rk.items():
        lead = rows[0]
        print(f"\n{metric}: leader {lead['ticker']} "
              f"({_fmt(lead['value'], lead['unit'])})")
        for r in rows:
            print(f"    {r['ticker']}: {_fmt(r['value'], r['unit'])} (FY{r['fy']})")
